version: '3.8'
services:
  database:
    container_name: db-producao-valhalla-kitchen
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testeFiapNaoFacaIssoEmPrd
      POSTGRES_DB: postgres
    volumes:
      - ./docker/01-create_db.sql:/docker-entrypoint-initdb.d/01-create_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    container_name: api-producao-valhalla-kitchen
    image: openjdk:latest
    ports:
      - "8082:8082"
    environment:
      PORT: 8082
      POSTGRES_DB: postgres
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: testeFiapNaoFacaIssoEmPrd
    volumes:
      - ./docker/producao-valhalla-kitchen-1.0.jar:/app/producao-valhalla-kitchen-1.0.jar
    command:
      ["java", "-jar", "/app/producao-valhalla-kitchen-1.0.jar"]
    depends_on:
      database:
        condition: service_healthy
