server:
  port: 8080
  servlet:
    context-path: "/api"
spring:
  data:
    mongodb:
      uri: mongodb://${DB_USERNAME}:${DB_PASSWORD}@${MONGODB_HOST}:27017/
      database: ${MONGODB_DATABASE}
  cloud:
    aws:
      credentials:
        accessKey: ${AWS_ACCESS_KEY}
        secretKey: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION}
queue:
  pedido-aprovado: queue-pedido-aprovado
  atualizacao-situacao-pedido: queue-atualizacao-situacao-pedido