server:
  port: ${PORT:8082}
  servlet:
    context-path: "/api"
spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST}:27017/
      database: ${MONGODB_DATABASE}