server:
  port: ${PORT:8082}
  servlet:
    context-path: "/api"
spring:
  data:
      mongodb:
        uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_CLUSTER}:${MONGODB_PORT}/${MONGODB_DB}?authSource=admin
        database: ${MONGODB_DB}