FROM openjdk:17

EXPOSE 8082

ENV POSTGRES_DB=postgres
ENV POSTGRES_HOST=database
ENV POSTGRES_PORT=5432
ENV POSTGRES_USERNAME=postgres
ENV POSTGRES_PASSWORD=testeFiapNaoFacaIssoEmPrd

WORKDIR /app

COPY producao-valhalla-kitchen-1.0.jar app.jar

CMD ["java", "-jar", "app.jar"]