version: '3.1'

services:

  mongo-producao:
    image: mongo:4.4.29
    restart: always
    ports:
      - "27017:27017"
    networks:
      - valhalla-kitchen
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  api-producao:
    depends_on:
      - mongo-producao
    image: caiolepetit/api-producao-valhalla-kitchen:latest
    restart: always
    ports:
      - "8081:8080"
    networks:
      - valhalla-kitchen
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo-producao:27017/

networks:
  valhalla-kitchen: